version: "3"

services:
  ok_db:
    image: postgres:latest
    ports:
      - "15432:15432"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    volumes:
      - ./docker-data/postgresql_data:/var/lib/postgresql/data
      - ./postgres/init.d:/docker-entrypoint-initdb.d

  apacheds:
    build:
      context: ./apacheds
    container_name: "apacheds"
    ports:
      - 10389:10389

  keycloak:
    build:
      context: ./keycloak
    container_name: "keycloak"
    environment:
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME_URL=${KC_HOSTNAME_URL}
      - KC_HOSTNAME_ADMIN_URL=${KC_HOSTNAME_ADMIN_URL}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_SAME_SITE_COOKIES=true
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=8080
      - KC_HTTPS_PORT=8443
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - vertx.disableFileCaching=true
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 8043:8080
      - 8443:8443
      - 10990:10990
    depends_on:
      - apacheds
      - ok_db

  openfire:
    image: okstarorg/okstar-openfire:v4.7
    container_name: "openfire"
    volumes:
      # - ./logs/openfire:/usr/local/openfire/logs
      - ./docker-data/logs/openfire:/var/log/openfire
    ports:
      - 3478:3478
      - 3479:3479
      - 5222:5222
      - 5223:5223
      - 5229:5229
      - 5262:5262
      - 5263:5263
      - 5275:5275
      - 5276:5276
      - 7070:7070
      - 7443:7443
      - 7777:7777
      - 9090:9090
      - 9091:9091
      - 5005:5005
    depends_on:
      - apacheds
